[package]
name = "tataku-common-proc-macros"
version = "0.6.0"
edition.workspace = true

[lib]
proc-macro = true

[features]
packet_logging = []
serialization_logging = []

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
